project_name: stream-forward
version: 2
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
# dockers:
# - image_templates: ["ghcr.io/eliottcassidy2000/stream-forward:{{ .Version }}"]
#   dockerfile: Dockerfile
#   build_flag_templates:
#   - --label=org.opencontainers.image.title={{ .ProjectName }}
#   - --label=org.opencontainers.image.description={{ .ProjectName }}
#   - --label=org.opencontainers.image.url=https://github.com/goreleaser/example
#   - --label=org.opencontainers.image.source=https://github.com/goreleaser/example
#   - --label=org.opencontainers.image.version={{ .Version }}
#   - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#   - --label=org.opencontainers.image.revision={{ .FullCommit }}
#   - --label=org.opencontainers.image.licenses=MIT
# nfpms:
# - maintainer: Eliott Cassidy <eliottcassidy2000@gmail.com>
#   description: Sample project.
#   homepage: https://github.com/eliottcassidy2000
#   license: MIT
#   formats:
#   - deb
#   - rpm
#   - apk
